name: "Aggiunta relazione di tirocinio - Italian"
description: "Aggiungi una relazione di tirocinio alle pagine 'tirocinio', versione Italiana"
title: "Aggiunta relazione di tirocinio"  
labels: Internship Report  
assignees: Lorenzoantonelli,Exyss
body:
  - type: input
    id: author
    attributes:
      label: "Autore Relazione"
      placeholder: "es: Mario Rossi"
    validations:
      required: true
  - type: input
    id: topic
    attributes:
      label: "Topic Relazione (Deve essere breve!)"
      placeholder: "es: Machine Learning"
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: "Titolo Relazione"
      placeholder: "es: Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      value: 
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: "Link Relazione"
      placeholder: "es: Github, Google Drive, ..."
      value: 
    validations:
      required: true
  - type: checkboxes
    id: declarations
    attributes:
      label: Aggiungendo questa relazione di tirocinio alla pagina dichiaro che
      description: Devi selezionare tutte le opzioni.
      options:
        - label: Sono l'autore della relazione di tirocinio o ho ricevuto l'autorizzazione per condividerla dall'autore
          required: true
        - label: Desidero che la relazione di tirocinio sia condivisa con gli studenti nelle pagine dedicate di sapienzastudents.net
          required: true
        - label: Posso richiedere la rimozione della relazione di tirocinio in qualsiasi momento aprendo una nuova issue su GitHub
          required: true
